### PR TITLE
backend setup for impostor

### PR DESCRIPTION
**Pull request by spioupiou**
I started to implement the impostor feature (backend only for now!)
- if the instance has no rounds yet (e.g. it's the very start of the game), I call a function called generate_impostor
- this function will make the first user with nickname "cedrine" the impostor
- if no player with the nickname "cedrine" is found, then the impostor is assigned randomly (using our favorite array.sample ❤️ )

I also changed the column_name from imposter to impostor, apparently both spellings can be found but impostor seems to be the correct spelling 😮 
https://writingexplained.org/imposter-or-impostor-spelling

https://user-images.githubusercontent.com/68413600/156110611-8d09d384-9164-4a60-a799-c18ff241adde.mov

### CODE REVIEW

**Comment by spioupiou** [comment]
FYI - I modified this PR so that it fits with our new plan to have impostor inside the instance! 
New migration file deletes impostor true/false from player and add a player_id to instances (our impostor)
I also changed the code inside the round controller accordingly, it still works the same (impostor is cedrine if found, if not it's random)

**Comment by spioupiou** [comment]
FYI - closing temporarily because I found a way to save the player_id of instance as impostor :) I think this will make things much easier in the future, will reopen in a few minutes!

**Comment by carlnoval** [comment]
I'll review this now since I'll need this PR for round0.

**Comment by carlnoval** [comment]
I'll just merge this and make additional changes on top of it so we can move forward.

**Pull request merged**
