### PR TITLE
Edit nickname

### PR DESCRIPTION
**Pull request by spioupiou**
I implemented an easy way to change the nickname :) 
From what I've seen on the Internet it is highly recommended to come up with our own methods rather than messing around with devise by removing the current password verification etc. So I've made a users_controller. I hope this is acceptable!
In the video I used a guest_user, but it works just the same for logged_in users. 

https://user-images.githubusercontent.com/68413600/155246681-b69ddedc-5387-4775-87d7-ef3cc6a4c70c.mov

### CODE REVIEW

**Comment by spioupiou** [comment]
We really need to fix the design 😆  I cannot scroll down so it's hard to see!

**Comment by hiroya210** [comment]
I think I fixed this on my PR haha

**Comment by spioupiou** [comment]
I added a partial for the form so that it's cleaner, improved the style a little and added validation (nickname cannot be empty) 
Right now the page refresh with a flash alert if the nickname is empty, I want to implement ajax later on but not sure how! Will probably grab a TA tomorrow :)

**Comment by carlnoval** [comment]
Thanks @spioupiou merging.

**Pull request merged**
